### ISSUE TITLE
作者您好，能否提供一下R52数据集呢，谢谢

### ISSUE THREAD

**Issue by CSpring2019** [usydnlp/InductTGCN#1]

**Comment by sergioburdisso** [comment]
Hello there! yeah, I was about to ask the same question, is there a way we can get access to the missing `R52.csv` file?

Thank you so much!

**Comment by MatrixBlake** [comment]
Thanks for asking. R52.csv is uploaded.

**Comment by CSpring2019** [comment]
Thank you very much for your help.

**Comment by sergioburdisso** [comment]
Thanks!
